services:
  inference-worker-cpu:
    build:
      context: ./inference-service
      dockerfile: Dockerfile.cpu
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_SERVER=db
      - MINIO_ENDPOINT=minio:9000
      - MODELS_PATH=/models
      - ONNX_PROVIDERS=["CPUExecutionProvider"]
    volumes:
      - ./data/models:/models:ro  # Read-only mount from host
    networks:
      - default
