"""Add DICOM models for medical image processing

Revision ID: 4f04eccae12c
Revises: 97e0d2a11e41
Create Date: 2025-09-21 21:57:05.240407

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f04eccae12c'
down_revision = '97e0d2a11e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dicomstudy',
    sa.Column('study_instance_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=True),
    sa.Column('study_time', sa.Time(), nullable=True),
    sa.Column('study_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_instance_uid')
    )
    op.create_table('dicomseries',
    sa.Column('series_instance_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('series_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('body_part_examined', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['dicomstudy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_instance_uid')
    )
    op.create_table('dicommetadata',
    sa.Column('instance_number', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('pixel_spacing', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('slice_thickness', sa.Numeric(), nullable=True),
    sa.Column('window_center', sa.Numeric(), nullable=True),
    sa.Column('window_width', sa.Numeric(), nullable=True),
    sa.Column('extracted_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['filemetadata.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['dicomseries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dicommetadata')
    op.drop_table('dicomseries')
    op.drop_table('dicomstudy')
    # ### end Alembic commands ###
