"""add source_image_path to segmentation result

Revision ID: 9e950790d9fd
Revises: 804eab4b421b
Create Date: 2025-10-02 10:06:05.881099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9e950790d9fd'
down_revision = '804eab4b421b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segmentationresult', sa.Column('source_image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segmentationresult', 'source_image_path')
    # ### end Alembic commands ###
